# Generated by Django 2.2.7 on 2019-12-02 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40)),
                ('codeforces_id', models.CharField(max_length=40)),
                ('Uva_Id', models.CharField(max_length=40)),
                ('points', models.IntegerField(blank=True, default=0)),
                ('department', models.CharField(max_length=40)),
                ('red_mark', models.BooleanField(default=False)),
                ('TotalContest', models.IntegerField(default=0)),
                ('TotalSolve', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
