# Generated by Django 2.2.1 on 2019-09-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=40, unique=True)),
                ('userName', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
                ('codeforcesHandle', models.CharField(max_length=40)),
                ('uvaHandle', models.CharField(max_length=40)),
                ('lightOJ', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
    ]
