# Generated by Django 2.2.7 on 2019-11-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191124_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='TotalContest',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='TotalSolve',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='red_mark',
            field=models.BooleanField(default=False),
        ),
    ]
