# Generated by Django 2.2.7 on 2019-11-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CONTEST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField()),
                ('Name', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
                ('solve', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=9999)),
            ],
        ),
    ]
