# Generated by Django 2.2.7 on 2019-11-30 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='ID',
            new_name='number',
        ),
    ]
